"""add image column to birds table

Revision ID: 17c6e63b7f60
Revises: cb579d38aee0
Create Date: 2023-09-27 15:02:34.230708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c6e63b7f60'
down_revision = 'cb579d38aee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birds', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
